// Generated by CoffeeScript 1.6.3
(function() {
  var Wit, options, wit;

  Wit = require('../lib/node-wit.coffee');

  wit = new Wit(process.env.WIT_ACCESS_TOKEN);

  options = {
    audio_file: './audio_sample/helloWorld.wav'
  };

  wit.analyze(options, function(err, res, body) {
    if (err) {
      console.log(err);
    } else {
      console.log(JSON.parse(body));
    }
    options = {
      user_text: 'Hello world'
    };
    return wit.analyze(options, function(err, res, body) {
      if (err) {
        return console.log(err);
      } else {
        return console.log(JSON.parse(body));
      }
    });
  });

}).call(this);
